// discoverableTokens.mjs — the popular/discoverable token list, built from
// ON-CHAIN POOL ENUMERATION (ground truth of what is tradeable) rather than
// ranking explorer tokens by holders. This is what surfaces MuchFi's tokens:
// the explorer's holder ranking misses them, but every pool they have is in
// the factory's creation log.
//
// Pipeline: enumerate live tradeable pools across all venues -> rank tokens by
// the base-token (WDOGE) liquidity backing them -> drop testnet spam (symbol
// duplicates, auto-generated numbered symbols, and identical-liquidity batch
// deploys) -> enrich the survivors with explorer holders + logo. Cached.

import { enumerateTradeableTokens } from "./venuePoolEnumeration.mjs";
import { createTokenMetadataReader } from "./tokenMetadata.mjs";

const BALANCE_OF_SELECTOR = "0x70a08231";
const DEFAULT_LIMIT = 15;
const DEFAULT_RANK_POOL = 40; // metadata is read for at most this many top tokens
const DEFAULT_CACHE_TTL_MS = 5 * 60 * 1000;
const IDENTICAL_LIQ_BATCH = 3; // >=N tokens with the exact same liquidity = batch spam

function lower(value) {
  return String(value ?? "").toLowerCase();
}

function looksAutoGenerated(symbol) {
  // Trailing 3+ digits (AGT4272, SMK722, T249-style) = batch test deploys.
  return /\d{3,}$/.test(symbol);
}

async function readBalance(client, token, owner) {
  try {
    const result = await client.call(
      { to: token, data: `${BALANCE_OF_SELECTOR}${lower(owner).slice(2).padStart(64, "0")}` },
      "latest",
    );
    return BigInt(result);
  } catch {
    return 0n;
  }
}

const PRIMARY_BASE_DECIMALS = 18n; // WDOGE
const PROBE_BASE_AMOUNT = 5n * 10n ** 16n; // 0.05 WDOGE — small so impact is fair to shallow pools
const MIN_ROUND_TRIP_BPS = 6000; // must recover >= 60% of a buy->sell round trip

export function createDiscoverableTokensProvider({
  client,
  fetchFn = fetch,
  blockscoutBaseUrl,
  sources = [],
  baseTokens = [],
  officialAddresses = [],
  primaryBase, // address used for the liquidity ranking (WDOGE)
  // Round-trip tradeability gate: async ({ sellToken, buyToken, amountIn }) =>
  // { ok, amountOut, priceImpactBps }. A token is surfaced ONLY if it quotes
  // both ways with positive output and sane price impact — this is what
  // rejects honeypots (buyable, not sellable) and drained one-sided pools that
  // a liquidity-balance check alone cannot catch.
  quoteProbe,
  limit = DEFAULT_LIMIT,
  rankPoolSize = DEFAULT_RANK_POOL,
  minBaseLiquidity = 1n, // wei of the base token; tokens below are dust/spam
  minRoundTripBps = MIN_ROUND_TRIP_BPS,
  cacheTtlMs = DEFAULT_CACHE_TTL_MS,
  nowMs = () => Date.now(),
} = {}) {
  const officialSet = new Set(officialAddresses.map(lower));
  const baseAddresses = baseTokens.map((t) => t.address);
  const rankBase = lower(primaryBase ?? baseAddresses[0] ?? "");
  const readMetadata = createTokenMetadataReader({ client });
  let cache = { at: 0, data: null };
  let inflight = null;

  async function explorerInfo(address) {
    try {
      const res = await fetchFn(`${blockscoutBaseUrl}/api/v2/tokens/${address}`);
      if (!res.ok) return {};
      const body = await res.json();
      return { holders: Number(body.holders_count ?? body.holders ?? 0), iconUrl: body.icon_url || null };
    } catch {
      return {};
    }
  }

  async function build() {
    const tokens = await enumerateTradeableTokens({
      client,
      sources,
      baseAddresses,
      officialAddresses,
    });
    if (tokens.length === 0) return [];

    // Rank by base-token (WDOGE) liquidity backing each token's pools.
    await Promise.all(
      tokens.map(async (token) => {
        const balances = await Promise.all(
          token.pools.map((pool) => readBalance(client, rankBase, pool.poolAddress)),
        );
        token.baseLiquidity = balances.reduce((sum, value) => sum + value, 0n);
      }),
    );

    // Identical-liquidity batch detection (the AGT #### series all share one
    // exact liquidity value because they were deployed together).
    const liqCounts = new Map();
    for (const token of tokens) {
      const key = token.baseLiquidity.toString();
      liqCounts.set(key, (liqCounts.get(key) ?? 0) + 1);
    }

    const ranked = tokens
      .filter((token) => token.baseLiquidity >= minBaseLiquidity)
      .filter((token) => (liqCounts.get(token.baseLiquidity.toString()) ?? 0) < IDENTICAL_LIQ_BATCH)
      .sort((a, b) => (b.baseLiquidity > a.baseLiquidity ? 1 : -1))
      .slice(0, rankPoolSize);

    // Resolve metadata, then dedupe by symbol (keep deepest) and drop
    // auto-generated numbered symbols.
    const withMeta = [];
    for (const token of ranked) {
      let meta;
      try {
        // eslint-disable-next-line no-await-in-loop
        meta = await readMetadata(token.address);
      } catch {
        continue;
      }
      if (officialSet.has(lower(meta.address))) continue;
      if (looksAutoGenerated(meta.symbol)) continue;
      withMeta.push({ ...token, ...meta });
    }

    const bySymbol = new Map();
    for (const token of withMeta) {
      const key = token.symbol.toLowerCase();
      const existing = bySymbol.get(key);
      if (!existing || token.baseLiquidity > existing.baseLiquidity) {
        bySymbol.set(key, token);
      }
    }

    const rankedBySymbol = [...bySymbol.values()].sort((a, b) =>
      b.baseLiquidity > a.baseLiquidity ? 1 : -1,
    );

    // Round-trip tradeability gate — reject honeypots / drained pools. Probe
    // in SMALL BATCHES (each probe fans out to multiple venues; flooding the
    // RPC with all candidates at once times them all out), stopping once
    // `limit` tokens pass.
    const gated = [];
    if (typeof quoteProbe === "function") {
      // Probe one token at a time (each probe fans out to multiple venues;
      // concurrency floods the testnet RPC and times healthy pools out).
      const PROBE_BATCH = 1;
      // One direction, retried — the live RPC intermittently times a single
      // source out under load; a healthy pool quotes on a retry.
      const probeDir = async (sellToken, buyToken, amountIn) => {
        for (let attempt = 0; attempt < 3; attempt += 1) {
          // eslint-disable-next-line no-await-in-loop
          const r = await quoteProbe({ sellToken, buyToken, amountIn }).catch(() => null);
          if (r?.ok && BigInt(r.amountOut ?? 0n) > 0n) return r;
        }
        return null;
      };
      // Round-trip recovery test: buy a SMALL amount of base into the token,
      // then sell exactly that back. A healthy pool returns ~most of the base
      // (minus fees + a little impact). Honeypots return ~nothing (sell
      // blocked / no route); drained one-sided pools return far too little.
      // Using a small, consistent probe makes this fair to shallow-but-real
      // pools and independent of the token's price/decimals.
      const isTradeable = async (token) => {
        const probeIn = PROBE_BASE_AMOUNT;
        const buy = await probeDir(rankBase, token.address, probeIn);
        if (!buy) return false;
        const tokensOut = BigInt(buy.amountOut);
        const sell = await probeDir(token.address, rankBase, tokensOut);
        if (!sell) return false;
        const recovered = BigInt(sell.amountOut);
        // recovered / probeIn >= minRoundTripBps / 10000
        return recovered * 10000n >= probeIn * BigInt(minRoundTripBps);
      };
      for (let i = 0; i < rankedBySymbol.length && gated.length < limit; i += PROBE_BATCH) {
        const batch = rankedBySymbol.slice(i, i + PROBE_BATCH);
        // eslint-disable-next-line no-await-in-loop
        const flags = await Promise.all(batch.map((token) => isTradeable(token)));
        batch.forEach((token, j) => {
          if (flags[j]) gated.push(token);
        });
      }
    } else {
      gated.push(...rankedBySymbol);
    }

    const top = gated.slice(0, limit);

    // Enrich survivors with explorer holders + logo.
    const enriched = await Promise.all(
      top.map(async (token) => {
        const info = await explorerInfo(token.address);
        return {
          address: token.address,
          symbol: token.symbol,
          name: token.name,
          decimals: token.decimals,
          venues: token.venues,
          holders: info.holders ?? 0,
          iconUrl: info.iconUrl ?? null,
          verified: false,
          trending: true,
          tradeable: true,
        };
      }),
    );

    return enriched;
  }

  return async function discoverableTokens() {
    const now = nowMs();
    if (cache.data && now - cache.at <= cacheTtlMs) return cache.data;
    if (inflight) return inflight;
    inflight = build()
      .then((data) => {
        cache = { at: nowMs(), data };
        return data;
      })
      .finally(() => {
        inflight = null;
      });
    try {
      return await inflight;
    } catch {
      return cache.data ?? [];
    }
  };
}
