// tokenIndex.mjs — the FULL non-official token index.
//
// Unlike discoverableTokens.mjs (a spam-filtered, quote-probed, top-15 "trending"
// list), this indexes EVERY non-official token that has a live pool on our venues
// and returns it enriched with ERC-20 metadata, marked `verified: false` so the UI
// badges it "not official" exactly like trending/custom tokens. It backs GET /tokens
// (concatenated after the official list) so the catalog and picker show all tokens.
//
// Pipeline: enumerate live tradeable pools across venues (factory creation logs) ->
// keep non-official tokens -> read symbol/name/decimals (bounded concurrency, skip
// non-ERC-20s) -> emit { ...metadata, venues, verified:false }. Cached + single-flight.

import { enumerateTradeableTokens } from "./venuePoolEnumeration.mjs";
import { createTokenMetadataReader } from "./tokenMetadata.mjs";

const DEFAULT_CACHE_TTL_MS = 15 * 60 * 1000; // metadata for the whole index is RPC-heavy
const DEFAULT_CONCURRENCY = 8; // bound metadata reads so we don't flood the testnet RPC
const DEFAULT_PROBE_CONCURRENCY = 3; // route probes fan out across venues — keep this low

const lower = (value) => String(value ?? "").toLowerCase();

// Faucet/test spam pattern shared with the trending provider: a symbol ending in
// 3+ digits (AGT1696, TKN0420, …) is an auto-minted test token, not a real one.
const looksAutoGenerated = (symbol) => /\d{3,}$/.test(String(symbol ?? ""));

// Run `fn` over `items` with at most `limit` in flight (the RPC throttles batches).
async function mapLimit(items, limit, fn) {
  const results = new Array(items.length);
  let cursor = 0;
  const worker = async () => {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await fn(items[index], index);
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return results;
}

export function createTokenIndexProvider({
  client,
  sources = [],
  baseTokens = [],
  officialAddresses = [],
  cacheTtlMs = DEFAULT_CACHE_TTL_MS,
  concurrency = DEFAULT_CONCURRENCY,
  // The route probe fans out across venues, so it runs at LOW concurrency on the
  // (deduped) survivors to avoid flooding the testnet RPC.
  probeConcurrency = DEFAULT_PROBE_CONCURRENCY,
  // Match how non-official tokens are CURRENTLY surfaced (trending provider):
  // hide auto-minted faucet spam and collapse duplicate-symbol redeploys. Both
  // default on; flip off to expose every raw pool token (incl. AGT#### + dups).
  dropAutoGenerated = true,
  dedupeBySymbol = true,
  // Optional live routability gate: routeProbe(token) -> boolean, where token
  // carries { address, decimals, pools, bases }. A token is only indexed if it
  // passes (a real round-trip quote + min-liquidity). Off => no gating (raw pool
  // membership), which the unit tests rely on.
  routeProbe,
  nowMs = () => Date.now(),
} = {}) {
  const officialSet = new Set(officialAddresses.map(lower));
  const baseAddresses = baseTokens.map((t) => t.address);
  const readMetadata = createTokenMetadataReader({ client });
  let cache = { at: 0, data: null };
  let inflight = null;

  async function build() {
    const tokens = await enumerateTradeableTokens({ client, sources, baseAddresses, officialAddresses });
    if (tokens.length === 0) return [];

    // Pass 1 — metadata + cheap filters (official / faucet spam). Carry the
    // pool/base context the route probe needs in pass 2.
    const candidates = (
      await mapLimit(tokens, concurrency, async (token) => {
        let meta;
        try {
          meta = await readMetadata(token.address);
        } catch {
          return null; // not a readable ERC-20 (EOA / no decimals)
        }
        if (officialSet.has(lower(meta.address))) return null; // never duplicate an official token
        if (dropAutoGenerated && looksAutoGenerated(meta.symbol)) return null; // faucet test spam
        return {
          address: meta.address,
          symbol: meta.symbol,
          name: meta.name,
          decimals: meta.decimals,
          venues: token.venues,
          pools: token.pools,
          bases: token.bases,
        };
      })
    ).filter(Boolean);

    // Collapse duplicates BEFORE the (RPC-heavy) route probe so we probe the
    // fewest tokens. Key on SYMBOL by default (matches trending — many test
    // tokens redeploy under one symbol); else on address. Merge venues + pools.
    const byKey = new Map();
    for (const c of candidates) {
      const key = dedupeBySymbol ? c.symbol.toLowerCase() : c.address;
      const existing = byKey.get(key);
      if (existing) {
        existing.venues = [...new Set([...(existing.venues ?? []), ...(c.venues ?? [])])];
        existing.pools = [...(existing.pools ?? []), ...(c.pools ?? [])];
      } else {
        byKey.set(key, c);
      }
    }
    const deduped = [...byKey.values()];

    // Pass 2 — live routability gate at LOW concurrency (each probe fans out
    // across venues). A token is kept only if it passes (real round trip + min
    // liquidity), so the catalog never shows a token that "no-routes" or is a
    // honeypot on selection.
    let survivors = deduped;
    if (routeProbe) {
      const flags = await mapLimit(deduped, probeConcurrency, async (c) => {
        try {
          return await routeProbe(c);
        } catch {
          return false;
        }
      });
      survivors = deduped.filter((_, i) => flags[i]);
    }

    return survivors
      .map((c) => ({
        address: c.address,
        symbol: c.symbol,
        name: c.name,
        decimals: c.decimals,
        venues: [...new Set(c.venues ?? [])],
        // The "not official" marker the UI keys off (apps/web/src/lib/tokens.js
        // tokenVerified). MUST be explicit false — a non-empty provenance string
        // would otherwise read as verified.
        verified: false,
        discovered: true,
      }))
      .sort((a, b) => a.symbol.localeCompare(b.symbol));
  }

  return async function tokenIndex() {
    const now = nowMs();
    if (cache.data && now - cache.at <= cacheTtlMs) return cache.data;
    if (inflight) return inflight;
    inflight = build()
      .then((data) => {
        cache = { at: nowMs(), data };
        return data;
      })
      .finally(() => {
        inflight = null;
      });
    try {
      return await inflight;
    } catch {
      return cache.data ?? []; // never break /tokens — fall back to last good / empty
    }
  };
}
