// tokenIndex.mjs — the FULL non-official token index.
//
// Unlike discoverableTokens.mjs (a spam-filtered, quote-probed, top-15 "trending"
// list), this indexes EVERY non-official token that has a live pool on our venues
// and returns it enriched with ERC-20 metadata, marked `verified: false` so the UI
// badges it "not official" exactly like trending/custom tokens. It backs GET /tokens
// (concatenated after the official list) so the catalog and picker show all tokens.
//
// Pipeline: enumerate live tradeable pools across venues (factory creation logs) ->
// keep non-official tokens -> read symbol/name/decimals (bounded concurrency, skip
// non-ERC-20s) -> emit { ...metadata, venues, verified:false }. Cached + single-flight.

import { enumerateTradeableTokens } from "./venuePoolEnumeration.mjs";
import { createTokenMetadataReader } from "./tokenMetadata.mjs";

const DEFAULT_CACHE_TTL_MS = 15 * 60 * 1000; // metadata for the whole index is RPC-heavy
const DEFAULT_CONCURRENCY = 8; // bound metadata reads so we don't flood the testnet RPC

const lower = (value) => String(value ?? "").toLowerCase();

// Faucet/test spam pattern shared with the trending provider: a symbol ending in
// 3+ digits (AGT1696, TKN0420, …) is an auto-minted test token, not a real one.
const looksAutoGenerated = (symbol) => /\d{3,}$/.test(String(symbol ?? ""));

// Run `fn` over `items` with at most `limit` in flight (the RPC throttles batches).
async function mapLimit(items, limit, fn) {
  const results = new Array(items.length);
  let cursor = 0;
  const worker = async () => {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await fn(items[index], index);
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return results;
}

export function createTokenIndexProvider({
  client,
  sources = [],
  baseTokens = [],
  officialAddresses = [],
  cacheTtlMs = DEFAULT_CACHE_TTL_MS,
  concurrency = DEFAULT_CONCURRENCY,
  // Match how non-official tokens are CURRENTLY surfaced (trending provider):
  // hide auto-minted faucet spam and collapse duplicate-symbol redeploys. Both
  // default on; flip off to expose every raw pool token (incl. AGT#### + dups).
  dropAutoGenerated = true,
  dedupeBySymbol = true,
  // Optional live route check: routeProbe({address, decimals}) -> boolean. When
  // provided, a token is only indexed if it actually routes through an executable
  // venue — so the catalog never shows a token that "no-routes" on selection
  // (e.g. pools only on a non-executable venue, or too thin to quote). Off => no
  // gating (raw pool membership), which the unit tests rely on.
  routeProbe,
  nowMs = () => Date.now(),
} = {}) {
  const officialSet = new Set(officialAddresses.map(lower));
  const baseAddresses = baseTokens.map((t) => t.address);
  const readMetadata = createTokenMetadataReader({ client });
  let cache = { at: 0, data: null };
  let inflight = null;

  async function build() {
    const tokens = await enumerateTradeableTokens({ client, sources, baseAddresses, officialAddresses });
    if (tokens.length === 0) return [];

    const enriched = await mapLimit(tokens, concurrency, async (token) => {
      let meta;
      try {
        meta = await readMetadata(token.address);
      } catch {
        return null; // not a readable ERC-20 (EOA / no decimals) — can't display it
      }
      if (officialSet.has(lower(meta.address))) return null; // never duplicate an official token
      if (dropAutoGenerated && looksAutoGenerated(meta.symbol)) return null; // faucet test spam
      // Only surface tokens we can actually ROUTE — otherwise they show in the
      // catalog but "no-route" the moment a user selects them.
      if (routeProbe) {
        let routable = false;
        try {
          routable = await routeProbe({ address: meta.address, decimals: meta.decimals });
        } catch {
          routable = false;
        }
        if (!routable) return null;
      }
      return {
        address: meta.address,
        symbol: meta.symbol,
        name: meta.name,
        decimals: meta.decimals,
        venues: token.venues,
        // The "not official" marker the UI keys off (apps/web/src/lib/tokens.js
        // tokenVerified). MUST be explicit false — a non-empty provenance string
        // would otherwise read as verified.
        verified: false,
        discovered: true,
      };
    });

    // Collapse duplicates. By default key on SYMBOL (matches the trending list —
    // many test tokens redeploy under one symbol); otherwise key on address so
    // every distinct contract survives. Either way, merge the venue lists.
    const byKey = new Map();
    for (const entry of enriched) {
      if (!entry) continue;
      const key = dedupeBySymbol ? entry.symbol.toLowerCase() : entry.address;
      const existing = byKey.get(key);
      if (existing) {
        existing.venues = [...new Set([...(existing.venues ?? []), ...(entry.venues ?? [])])];
      } else {
        byKey.set(key, entry);
      }
    }
    return [...byKey.values()].sort((a, b) => a.symbol.localeCompare(b.symbol));
  }

  return async function tokenIndex() {
    const now = nowMs();
    if (cache.data && now - cache.at <= cacheTtlMs) return cache.data;
    if (inflight) return inflight;
    inflight = build()
      .then((data) => {
        cache = { at: nowMs(), data };
        return data;
      })
      .finally(() => {
        inflight = null;
      });
    try {
      return await inflight;
    } catch {
      return cache.data ?? []; // never break /tokens — fall back to last good / empty
    }
  };
}
