// tokenIndex.mjs — the FULL non-official token index.
//
// Unlike discoverableTokens.mjs (a spam-filtered, quote-probed, top-15 "trending"
// list), this indexes EVERY non-official token that has a live pool on our venues
// and returns it enriched with ERC-20 metadata, marked `verified: false` so the UI
// badges it "not official" exactly like trending/custom tokens. It backs GET /tokens
// (concatenated after the official list) so the catalog and picker show all tokens.
//
// Pipeline: enumerate live tradeable pools across venues (factory creation logs) ->
// keep non-official tokens -> read symbol/name/decimals (bounded concurrency, skip
// non-ERC-20s) -> emit { ...metadata, venues, verified:false }. Cached + single-flight.

import { enumerateTradeableTokens } from "./venuePoolEnumeration.mjs";
import { createTokenMetadataReader } from "./tokenMetadata.mjs";
import { computeTrustScore, trustTier } from "./trustScore.mjs";

const DEFAULT_CACHE_TTL_MS = 15 * 60 * 1000; // metadata for the whole index is RPC-heavy
const DEFAULT_CONCURRENCY = 8; // bound metadata reads so we don't flood the testnet RPC
const DEFAULT_PROBE_CONCURRENCY = 3; // route probes fan out across venues — keep this low

const lower = (value) => String(value ?? "").toLowerCase();

// Faucet/test spam pattern shared with the trending provider: a symbol ending in
// 3+ digits (AGT1696, TKN0420, …) is an auto-minted test token, not a real one.
const looksAutoGenerated = (symbol) => /\d{3,}$/.test(String(symbol ?? ""));

// Run `fn` over `items` with at most `limit` in flight (the RPC throttles batches).
async function mapLimit(items, limit, fn) {
  const results = new Array(items.length);
  let cursor = 0;
  const worker = async () => {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await fn(items[index], index);
    }
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
  return results;
}

export function createTokenIndexProvider({
  client,
  sources = [],
  baseTokens = [],
  officialAddresses = [],
  cacheTtlMs = DEFAULT_CACHE_TTL_MS,
  concurrency = DEFAULT_CONCURRENCY,
  // The route probe fans out across venues, so it runs at LOW concurrency on the
  // (deduped) survivors to avoid flooding the testnet RPC.
  probeConcurrency = DEFAULT_PROBE_CONCURRENCY,
  // Match how non-official tokens are CURRENTLY surfaced (trending provider):
  // hide auto-minted faucet spam and collapse duplicate-symbol redeploys. Both
  // default on; flip off to expose every raw pool token (incl. AGT#### + dups).
  dropAutoGenerated = true,
  dedupeBySymbol = true,
  // Optional live routability gate: routeProbe(token) -> boolean, where token
  // carries { address, decimals, pools, bases }. A token is only indexed if it
  // passes (a real round-trip quote + min-liquidity). Off => no gating (raw pool
  // membership), which the unit tests rely on.
  routeProbe,
  // Optional trust-signal reader: signalProvider(token) -> { liquidityWei, holders }.
  // When wired, each surviving token gets a 0-100 trustScore + low/med/high
  // trustTier and the index is ranked by score (desc). NEVER flips `verified`.
  // Off => alphabetical order (what the unit tests assert).
  signalProvider,
  // Optional guilt-by-association: deployerProvider(address) -> deployer|null and
  // a reputation store { isFlagged(deployer), flag(deployer) }. A candidate whose
  // deployer is flagged is dropped; a token that FAILS the route probe (honeypot
  // / dead) flags its deployer, so its siblings are dropped next build.
  deployerProvider,
  reputation,
  nowMs = () => Date.now(),
} = {}) {
  const officialSet = new Set(officialAddresses.map(lower));
  const baseAddresses = baseTokens.map((t) => t.address);
  const readMetadata = createTokenMetadataReader({ client });
  let cache = { at: 0, data: null };
  let inflight = null;

  async function build() {
    const tokens = await enumerateTradeableTokens({ client, sources, baseAddresses, officialAddresses });
    if (tokens.length === 0) return [];

    // Pass 1 — metadata + cheap filters (official / faucet spam). Carry the
    // pool/base context the route probe needs in pass 2.
    const candidates = (
      await mapLimit(tokens, concurrency, async (token) => {
        let meta;
        try {
          meta = await readMetadata(token.address);
        } catch {
          return null; // not a readable ERC-20 (EOA / no decimals)
        }
        if (officialSet.has(lower(meta.address))) return null; // never duplicate an official token
        if (dropAutoGenerated && looksAutoGenerated(meta.symbol)) return null; // faucet test spam
        // Guilt by association: drop a token whose deployer already shipped a
        // flagged (honeypot/dead) token. Resolve the deployer once and carry it
        // so a route-probe failure below can flag it.
        let deployer = null;
        if (deployerProvider) {
          deployer = await deployerProvider(meta.address).catch(() => null);
          if (reputation?.isFlagged(deployer)) return null;
        }
        return {
          address: meta.address,
          symbol: meta.symbol,
          name: meta.name,
          decimals: meta.decimals,
          venues: token.venues,
          pools: token.pools,
          bases: token.bases,
          firstPoolBlock: token.firstPoolBlock ?? null,
          deployer,
        };
      })
    ).filter(Boolean);

    // Collapse duplicates BEFORE the (RPC-heavy) route probe so we probe the
    // fewest tokens. Key on SYMBOL by default (matches trending — many test
    // tokens redeploy under one symbol); else on address. Merge venues + pools.
    const byKey = new Map();
    for (const c of candidates) {
      const key = dedupeBySymbol ? c.symbol.toLowerCase() : c.address;
      const existing = byKey.get(key);
      if (existing) {
        existing.venues = [...new Set([...(existing.venues ?? []), ...(c.venues ?? [])])];
        existing.pools = [...(existing.pools ?? []), ...(c.pools ?? [])];
        // Keep the EARLIEST creation block across the merged redeploys (age).
        if (c.firstPoolBlock != null) {
          existing.firstPoolBlock =
            existing.firstPoolBlock != null ? Math.min(existing.firstPoolBlock, c.firstPoolBlock) : c.firstPoolBlock;
        }
      } else {
        byKey.set(key, c);
      }
    }
    const deduped = [...byKey.values()];

    // Pass 2 — live routability gate at LOW concurrency (each probe fans out
    // across venues). A token is kept only if it passes (real round trip + min
    // liquidity), so the catalog never shows a token that "no-routes" or is a
    // honeypot on selection.
    let survivors = deduped;
    if (routeProbe) {
      const flags = await mapLimit(deduped, probeConcurrency, async (c) => {
        try {
          return await routeProbe(c);
        } catch {
          return false;
        }
      });
      survivors = [];
      deduped.forEach((c, i) => {
        if (flags[i]) survivors.push(c);
        // A token that fails the round-trip probe (honeypot / dead pool) taints
        // its deployer, so the deployer's other tokens are dropped next build.
        else if (reputation && c.deployer) reputation.flag(c.deployer);
      });
    }

    const baseEntry = (c) => ({
      address: c.address,
      symbol: c.symbol,
      name: c.name,
      decimals: c.decimals,
      venues: [...new Set(c.venues ?? [])],
      // The "not official" marker the UI keys off (apps/web/src/lib/tokens.js
      // tokenVerified). MUST be explicit false — a non-empty provenance string
      // would otherwise read as verified.
      verified: false,
      discovered: true,
    });

    // No trust signals wired -> keep the alphabetical order (what tests assert).
    if (!signalProvider) {
      return survivors.map(baseEntry).sort((a, b) => a.symbol.localeCompare(b.symbol));
    }

    // Trust score: read liquidity depth + holders per survivor, derive age from
    // the current head, and rank by score (desc). Never flips `verified`.
    const head = await Promise.resolve(client.getBlockNumber?.())
      .then((b) => (b != null ? Number(b) : null))
      .catch(() => null);
    const signals = await mapLimit(survivors, probeConcurrency, async (c) => {
      try {
        return await signalProvider(c);
      } catch {
        return {};
      }
    });

    return survivors
      .map((c, i) => {
        const sig = signals[i] ?? {};
        const liquidityWdoge =
          sig.liquidityWei != null ? Number(BigInt(sig.liquidityWei) / 10n ** 16n) / 100 : 0; // wei -> WDOGE
        const ageBlocks =
          head != null && c.firstPoolBlock != null ? Math.max(0, head - c.firstPoolBlock) : 0;
        const trustScore = computeTrustScore({ liquidityWdoge, holders: sig.holders ?? 0, ageBlocks });
        return { ...baseEntry(c), holders: sig.holders ?? 0, trustScore, trustTier: trustTier(trustScore) };
      })
      .sort((a, b) => b.trustScore - a.trustScore || a.symbol.localeCompare(b.symbol));
  }

  return async function tokenIndex() {
    const now = nowMs();
    // Fresh cache -> serve it.
    if (cache.data && now - cache.at <= cacheTtlMs) return cache.data;

    // Stale or cold -> kick off a single-flight rebuild (the build is RPC-heavy:
    // enumerate + metadata + round-trip probes + holders/creator lookups, ~15s+).
    if (!inflight) {
      inflight = build()
        .then((data) => {
          cache = { at: nowMs(), data };
          return data;
        })
        .catch(() => cache.data ?? [])
        .finally(() => {
          inflight = null;
        });
    }

    // STALE-WHILE-REVALIDATE: if we have a last-known set, serve it INSTANTLY and
    // let the rebuild finish in the background — so /tokens never blocks a user on
    // the 15-min cache refresh. Only the very first build (no data yet) has nothing
    // to serve, so it awaits; the startup warm pays that one-time cost, not a user.
    if (cache.data) return cache.data;
    return inflight;
  };
}
